### ISSUE TITLE
Pairing characters and strings

### ISSUE THREAD

**Issue by aloispichler** [m4xshen/autoclose.nvim#23]
This is the only extension I know which pairs `$` correctly in LaTeX.
However, in LaTeX we pair `\[` with `\]` and `\left(` with `\right)`, etc. How can this be accomplished here, and without interfering with the pairs `(` and `)`?

**Comment by m4xshen** [comment]
This feature can't be accomplished here because autoclose.nvim only supports single character pairs. However, it could be done with treesitter. I'll study this in the future.

**Comment by m4xshen** [comment]
I decide to not add this feature because the implementation of it is [complicated](https://github.com/m4xshen/autoclose.nvim/issues/41#issuecomment-1732401189) and may cause more new issues. The philosophy of autoclose.nvim is being stable and minimal. If you want this feature you can use [nvim-autopairs](https://github.com/windwp/nvim-autopairs/wiki/Rules-API) instead.
